version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: barbershop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress01
      POSTGRES_DB: barbershop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - barbershop-network

  nextapp:
    build: .
    container_name: barbershop_app
    command: npm run dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgress01@postgres:5432/barbershop?schema=public"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - postgres
    networks:
      - barbershop-network

networks:
  barbershop-network:
    driver: bridge

volumes:
  pgdata:
